version: '3.9'
services:
  # nginx:
  #   container_name: ecom-nginx
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - '80:80'
  redis:
    container_name: ecom-redis
    image: redis:latest
    ports:
      - '6379:6379'
  postgres:
    container_name: ecom-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ecom
    ports:
      - '5432:5432'
